version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - '23:68:8f:60:b1:08:76:8b:54:3d:fe:51:da:38:8b:3f'
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/Ahmed-ao/scheduler.git main:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
